STYLE_NAMES = {
    "puppy_video": "puppy_50_epochs.safetensors",
    "Baby_video": "baby_50_epochs.safetensors",
    "jungle_video": "jungle_50_epochs.safetensors",
    "kiss_video": "kissing_30_epochs.safetensors",
    "mona_lisa_video": "mona_lisa_45_epochs.safetensors",
    "muscle_video": "muscle_18_epochs.safetensors",
    "painting_video": "painting_50_epochs.safetensors",
    "princess_video": "princess_45_epochs.safetensors",
    "samurai_video": "samurai_50_epochs.safetensors",
    "vip_video": "vip_50_epochs.safetensors",
    "flying_video": "flyingEffect.safetensors",
    "plush_video": "Wan-I2V LoRA - Morphing Into Plushtoy (Trigger) - Skyreels V2 i2v trained .safetensors",
    "squish_video": "squish_18.safetensors",
    "to_sand_video": "wan_disintegrate_e141.safetensors",
    "dance_video": "phut_hon_dance_dabaichui.safetensors",
    "boobs_video": "96774d10-5c2a-4904-862e-215d573300e5.safetensors",
    "walk_back_video": "walking_from_behind.safetensors",
    "serf_video": "wan_SmNmRmC.safetensors",
    "king_video": "wan_SmNmRmC.safetensors",
    "action_toy_athlete_video": "wan_SmNmRmC.safetensors",
    "action_toy_model_video": "wan_SmNmRmC.safetensors",
    "action_toy_retro_video": "wan_SmNmRmC.safetensors",
    "smoking_video": "wan_SmNmRmC.safetensors",
    "explotion_video": "explode_30_epochs.safetensors",
    "meltit_video": "MeltIt.safetensors",
    "labubu_toy_video": "wan_SmNmRmC.safetensors",
    "shark_video": "wan_SmNmRmC.safetensors",
    "Catify_video": "wan_SmNmRmC.safetensors",
    "Live_photo": "wan_SmNmRmC.safetensors",
    "colorizer_video": "wan_SmNmRmC.safetensors",
    "Dogify_video": "wan_SmNmRmC.safetensors"
}

STYLE_URLS = {
    "puppy_video": "https://huggingface.co/Remade-AI/Puppy/blob/main/puppy_50_epochs.safetensors",
    "Baby_video": "https://huggingface.co/Remade-AI/Baby/blob/main/baby_50_epochs.safetensors",
    "jungle_video": "https://huggingface.co/Remade-AI/Jungle/blob/main/jungle_50_epochs.safetensors",
    "kiss_video": "https://huggingface.co/Remade-AI/kissing/blob/main/kissing_30_epochs.safetensors",
    "muscle_video": "https://huggingface.co/Remade-AI/Muscle/blob/main/muscle_18_epochs.safetensors",
    "mona_lisa_video": "https://huggingface.co/Remade-AI/Mona-Lisa/blob/main/mona_lisa_45_epochs.safetensors",
    "painting_video": "https://huggingface.co/Remade-AI/Painting/blob/main/painting_50_epochs.safetensors",
    "princess_video": "https://huggingface.co/Remade-AI/Princess/blob/main/princess_45_epochs.safetensors",
    "samurai_video": "https://huggingface.co/Remade-AI/Samurai/blob/main/samurai_50_epochs.safetensors",
    "vip_video": "https://huggingface.co/Remade-AI/VIP/blob/main/vip_50_epochs.safetensors",
    "flying_video": "https://huggingface.co/Isi99999/Wan2.1_14B-480p_I2V_LoRAs/blob/main/flyingEffect.safetensors",
    "plush_video": "https://huggingface.co/sintecs/wan_loras/blob/main/Morphing.safetensors",
    "squish_video": "https://huggingface.co/Remade-AI/Squish/resolve/main/squish_18.safetensors",
    "to_sand_video": "https://huggingface.co/sintecs/wan_loras/blob/main/wan_disintegrate_e141.safetensors",
    "dance_video": "https://huggingface.co/Isi99999/Wan2.1_14B-480p_I2V_LoRAs/blob/main/phut_hon_dance_dabaichui.safetensors",
    "boobs_video": "https://huggingface.co/sintecs/wan_loras/blob/main/96774d10-5c2a-4904-862e-215d573300e5.safetensors",
    "walk_back_video": "https://huggingface.co/Isi99999/Wan2.1_14B-480p_I2V_LoRAs/blob/main/walking_from_behind.safetensors",
    "serf_video": "https://huggingface.co/sintecs/wan_loras/blob/main/wan_SmNmRmC.safetensors",
    "king_video": "https://huggingface.co/Remade-AI/Mona-Lisa/blob/main/wan_SmNmRmC.safetensors",
    "action_toy_athlete_video": "https://huggingface.co/Remade-AI/Mona-Lisa/blob/main/wan_SmNmRmC.safetensors",
    "action_toy_model_video": "https://huggingface.co/Remade-AI/Mona-Lisa/blob/main/wan_SmNmRmC.safetensors",
    "action_toy_retro_video": "https://huggingface.co/Remade-AI/Mona-Lisa/blob/main/wan_SmNmRmC.safetensors",
    "smoking_video": "https://huggingface.co/Remade-AI/Mona-Lisa/blob/main/wan_SmNmRmC.safetensors",
    "explotion_video": "https://huggingface.co/Remade-AI/Explode/blob/main/explode_30_epochs.safetensors",
    "meltit_video": "https://huggingface.co/sintecs/wan_loras/blob/main/MeltIt.safetensors",
    "labubu_toy_video": "https://huggingface.co/Remade-AI/Mona-Lisa/blob/main/wan_SmNmRmC.safetensors",
    "shark_video": "https://huggingface.co/Remade-AI/Mona-Lisa/blob/main/wan_SmNmRmC.safetensors",
    "Catify_video": "https://huggingface.co/Remade-AI/Mona-Lisa/blob/main/wan_SmNmRmC.safetensors",
    "Live_photo": "https://huggingface.co/Remade-AI/Mona-Lisa/blob/main/wan_SmNmRmC.safetensors",
    "colorizer_video": "https://huggingface.co/Remade-AI/Mona-Lisa/blob/main/wan_SmNmRmC.safetensors",
    "Dogify_video": "https://huggingface.co/Remade-AI/Mona-Lisa/blob/main/wan_SmNmRmC.safetensors"
}

STYLE_URLS_UNIQUE = {
    "explotion_video": "https://huggingface.co/Remade-AI/Explode/blob/main/explode_30_epochs.safetensors",
    "meltit_video": "https://huggingface.co/sintecs/wan_loras/blob/main/MeltIt.safetensors",
    "puppy_video": "https://huggingface.co/Remade-AI/Puppy/blob/main/puppy_50_epochs.safetensors",
    "Baby_video": "https://huggingface.co/Remade-AI/Baby/blob/main/baby_50_epochs.safetensors",
    "jungle_video": "https://huggingface.co/Remade-AI/Jungle/blob/main/jungle_50_epochs.safetensors",
    "kiss_video": "https://huggingface.co/Remade-AI/kissing/blob/main/kissing_30_epochs.safetensors",
    "muscle_video": "https://huggingface.co/Remade-AI/Muscle/blob/main/muscle_18_epochs.safetensors",
    "mona_lisa_video": "https://huggingface.co/Remade-AI/Mona-Lisa/blob/main/mona_lisa_45_epochs.safetensors",
    "painting_video": "https://huggingface.co/Remade-AI/Painting/blob/main/painting_50_epochs.safetensors",
    "princess_video": "https://huggingface.co/Remade-AI/Princess/blob/main/princess_45_epochs.safetensors",
    "samurai_video": "https://huggingface.co/Remade-AI/Samurai/blob/main/samurai_50_epochs.safetensors",
    "vip_video": "https://huggingface.co/Remade-AI/VIP/blob/main/vip_50_epochs.safetensors",
    "flying_video": "https://huggingface.co/Isi99999/Wan2.1_14B-480p_I2V_LoRAs/blob/main/flyingEffect.safetensors",
    "plush_video": "https://huggingface.co/sintecs/wan_loras/blob/main/Morphing.safetensors",
    "squish_video": "https://huggingface.co/Remade-AI/Squish/resolve/main/squish_18.safetensors",
    "to_sand_video": "https://huggingface.co/sintecs/wan_loras/blob/main/wan_disintegrate_e141.safetensors",
    "dance_video": "https://huggingface.co/Isi99999/Wan2.1_14B-480p_I2V_LoRAs/blob/main/phut_hon_dance_dabaichui.safetensors",
    "boobs_video": "https://huggingface.co/sintecs/wan_loras/blob/main/96774d10-5c2a-4904-862e-215d573300e5.safetensors",
    "walk_back_video": "https://huggingface.co/Isi99999/Wan2.1_14B-480p_I2V_LoRAs/blob/main/walking_from_behind.safetensors",
    "serf_video": "https://huggingface.co/sintecs/wan_loras/blob/main/wan_SmNmRmC.safetensors",
}